[package]
name = "sfxc-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sfxc"
path = "src/main.rs"

[dependencies]
sfxc-core = { path = "../sfxc-core" }
sfxc-store = { path = "../sfxc-store" }
anyhow = "1"
eframe = "0.36"
cpal = "0.18"
rfd = "0.17"
egui-phosphor = { version = "0.14", features = ["regular", "fill"] }
